Repository scikit-multiflow/scikit-multiflow, pull requests merged in 2020-02, with the labels that each got.

#183 [BUG] Fixing vote aggregation in HAT, typos in HAT/HATR, and improper usage of ADWIN in the adaptive trees
  src/skmultiflow/trees/hoeffding_adaptive_tree.py
  src/skmultiflow/trees/nodes/ada_learning_node.py
  src/skmultiflow/trees/nodes/ada_learning_node_for_regression.py
  src/skmultiflow/trees/nodes/ada_split_node.py
  src/skmultiflow/trees/nodes/ada_split_node_for_regression.py
  src/skmultiflow/utils/__init__.py
  src/skmultiflow/utils/utils.py
  tests/utils/test_utils.py
Labels: bug

#208 Fix bug in evaluators when model_size or running_time are listed first in the metrics option
  src/skmultiflow/evaluation/base_evaluator.py
  src/skmultiflow/evaluation/evaluate_holdout.py
  src/skmultiflow/evaluation/evaluate_prequential.py
Labels: bug

#199 [DOC] Add example template code to CONTRIBUTING.md
  CONTRIBUTING.md
  src/skmultiflow/anomaly_detection/half_space_trees.py
Labels: doc

#211 Add check in InfoGainSplitCriterion to avoid division by zero
  src/skmultiflow/trees/split_criterion/info_gain_split_criterion.py
Labels: bug

#184 Contribute StandardScaler and MinMax transformations
  src/skmultiflow/transform/windowed_minmax_scaler.py
  src/skmultiflow/transform/windowed_standard_scaler.py
  tests/transform/minmax_scaler.npy
  tests/transform/std_scaler.npy
  tests/transform/test_windowed_minmax_scaler.py
  tests/transform/test_windowed_standard_scaler.py
Labels: enhancement

#216 [Doc] Migrating documentation to readthedocs
  .gitignore
  .readthedocs.yml
  docs/Makefile
  docs/api/api.rst
  docs/changelog/v0.4.rst
  docs/index.rst
  docs/requirements.txt
  docs/user-guide.rst
  docs/user-guide/core-concepts.architecture.rst
  docs/user-guide/core-concepts.rst
  docs/user-guide/core-concepts.stream-class.rst
  docs/user-guide/quick-start-docker.rst
  docs/user-guide/quick-start.rst
  docs/user-guide/streams-intro.rst
  docs/user-guide/user-guide.rst
  docs/versions.rst
  src/skmultiflow/drift_detection/hddm_a.py
  src/skmultiflow/drift_detection/hddm_w.py
  src/skmultiflow/transform/__init__.py
  src/skmultiflow/transform/missing_values_cleaner.py
  src/skmultiflow/transform/one_hot_to_categorical.py
Labels: doc
