Repository scikit-multiflow/scikit-multiflow, pull requests merged in 2020-04, with the labels that each got.

#228 Improvements on neighbors-based estimators
  docs/api/api.rst
  src/skmultiflow/demos/_test_kdtree_compare.py
  src/skmultiflow/lazy/__init__.py
  src/skmultiflow/lazy/base_neighbors.py
  src/skmultiflow/lazy/distances.py
  src/skmultiflow/lazy/kdtree.py
  src/skmultiflow/lazy/knn_adwin.py
  src/skmultiflow/lazy/knn_classifier.py
  src/skmultiflow/lazy/knn_regressor.py
  src/skmultiflow/utils/__init__.py
  src/skmultiflow/utils/data_structures.py
  tests/core/test_pipeline.py
  tests/lazy/test_kdtree.py
  tests/lazy/test_knn_adwin.py
  tests/lazy/test_knn_classifier.py
  tests/lazy/test_knn_regressor.py
  tests/meta/test_leverage_bagging.py
  tests/meta/test_oza_bagging.py
  tests/meta/test_oza_bagging_adwin.py
Labels: enhancement

#229 Minor updates for HalfSpaceTrees
  src/skmultiflow/anomaly_detection/half_space_trees.py
  tests/anomaly_detection/test_half_space_trees.py
Labels: enhancement

#230 [FEATURE] Add memory management mechanisms to regression trees and streamline generic code in tree-based estimators
  src/skmultiflow/trees/arf_hoeffding_tree.py
  src/skmultiflow/trees/extremely_fast_decision_tree.py
  src/skmultiflow/trees/hoeffding_adaptive_tree.py
  src/skmultiflow/trees/hoeffding_adaptive_tree_regressor.py
  src/skmultiflow/trees/hoeffding_tree.py
  src/skmultiflow/trees/hoeffding_tree_regressor.py
  src/skmultiflow/trees/isoup_tree.py
  src/skmultiflow/trees/label_combination_hoeffding_tree.py
  src/skmultiflow/trees/nodes/active_learning_node_adaptive_multi_target.py
  src/skmultiflow/trees/nodes/active_learning_node_perceptron.py
  src/skmultiflow/trees/nodes/active_learning_node_perceptron_multi_target.py
  src/skmultiflow/trees/nodes/ada_learning_node.py
  src/skmultiflow/trees/nodes/ada_learning_node_for_regression.py
  src/skmultiflow/trees/nodes/ada_split_node.py
  src/skmultiflow/trees/nodes/ada_split_node_for_regression.py
  src/skmultiflow/trees/nodes/found_node.py
  src/skmultiflow/trees/nodes/inactive_learning_node_adaptive_multi_target.py
  src/skmultiflow/trees/nodes/inactive_learning_node_perceptron.py
  src/skmultiflow/trees/nodes/inactive_learning_node_perceptron_multi_target.py
  src/skmultiflow/trees/nodes/sst_active_learning_node.py
  src/skmultiflow/trees/nodes/sst_active_learning_node_adaptive.py
  src/skmultiflow/trees/nodes/sst_inactive_learning_node.py
  src/skmultiflow/trees/nodes/sst_inactive_learning_node_adaptive.py
  src/skmultiflow/trees/stacked_single_target_hoeffding_tree_regressor.py
  tests/trees/expected_preds_multi_target_regression_adaptive.npy
  tests/trees/expected_preds_multi_target_regression_perceptron.npy
  tests/trees/expected_preds_stacked_single_target_hoeffding_tree_adaptive.npy
  tests/trees/expected_preds_stacked_single_target_hoeffding_tree_perceptron.npy
  tests/trees/multi_target_regression_data.npz
  tests/trees/regression_data.npz
  tests/trees/test_extremely_fast_decision_tree.py
  tests/trees/test_hoeffding_adaptive_tree.py
  tests/trees/test_hoeffding_adaptive_tree_regressor.py
  tests/trees/test_hoeffding_tree.py
  tests/trees/test_hoeffding_tree_regressor.py
  tests/trees/test_isoup_tree.py
  tests/trees/test_label_combination_hoeffding_tree.py
  tests/trees/test_stacked_single_target_hoeffding_tree_regressor.py
Labels: bug, enhancement, refactoring

#235 [BUG] Reapply lost fixes from #220
  src/skmultiflow/trees/hoeffding_adaptive_tree_regressor.py
  src/skmultiflow/trees/isoup_tree.py
  src/skmultiflow/trees/nodes/ada_learning_node.py
  src/skmultiflow/trees/nodes/ada_learning_node_for_regression.py
  src/skmultiflow/trees/nodes/ada_split_node.py
  src/skmultiflow/trees/nodes/ada_split_node_for_regression.py
  src/skmultiflow/trees/nodes/lc_active_learning_node.py
  tests/trees/test_hoeffding_adaptive_tree.py
  tests/trees/test_hoeffding_adaptive_tree_regressor.py
Labels: bug

#234 Add KSWIN as a concept drift detector
  AUTHORS.md
  src/skmultiflow/drift_detection/__init__.py
  src/skmultiflow/drift_detection/kswin.py
  tests/drift_detection/test_kswin.py
Labels: feature
