Repository scikit-multiflow/scikit-multiflow, pull requests merged in 2020-05, with the labels that each got.

#236 Make EvaluatePrequential and EvaluateHoldout report all processed samples in the output file
  src/skmultiflow/evaluation/evaluate_holdout.py
  src/skmultiflow/evaluation/evaluate_prequential.py
Labels: enhancement

#222 [FEATURE] Delayed Evaluations
  requirements.txt
  src/skmultiflow/data/__init__.py
  src/skmultiflow/data/temporal_data_stream.py
  src/skmultiflow/data/time_manager.py
  src/skmultiflow/evaluation/__init__.py
  src/skmultiflow/evaluation/base_evaluator.py
  src/skmultiflow/evaluation/evaluate_prequential_delayed.py
  src/skmultiflow/utils/__init__.py
  src/skmultiflow/utils/data_structures.py
  src/skmultiflow/utils/utils.py
  tests/data/test_temporal_data_stream.py
  tests/evaluation/prequential_delayed_summary.csv
  tests/evaluation/test_evaluate_prequential_delayed.py
Labels: evaluation, feature

#245 Fix bug in the LeveragingBaggingClassifier and NaiveBayes
  src/skmultiflow/bayes/naive_bayes.py
  src/skmultiflow/meta/leverage_bagging.py
  tests/meta/test_leverage_bagging.py
Labels: bug

#251 Anomaly detection module updates
  src/skmultiflow/anomaly_detection/half_space_trees.py
  src/skmultiflow/data/__init__.py
  src/skmultiflow/data/anomaly_sine_generator.py
  tests/anomaly_detection/test_half_space_trees.py
  tests/data/anomaly_sine_stream.npz
  tests/data/test_anomaly_sine_generator.py
Labels: bug, feature
