Repository scikit-multiflow/scikit-multiflow, pull requests merged in 2020-03, with the labels that each got.

#200 Code examples
  CONTRIBUTING.md
  src/skmultiflow/anomaly_detection/half_space_trees.py
  src/skmultiflow/bayes/naive_bayes.py
  src/skmultiflow/data/unsupervised_stream.py
  src/skmultiflow/meta/accuracy_weighted_ensemble.py
  src/skmultiflow/meta/adaptive_random_forests.py
  src/skmultiflow/meta/additive_expert_ensemble.py
  src/skmultiflow/meta/batch_incremental.py
  src/skmultiflow/meta/classifier_chains.py
  src/skmultiflow/meta/dynamic_weighted_majority.py
  src/skmultiflow/meta/learn_nse.py
  src/skmultiflow/meta/online_adac2.py
  src/skmultiflow/meta/online_boosting.py
  src/skmultiflow/meta/online_csb2.py
  src/skmultiflow/meta/online_rus_boost.py
  src/skmultiflow/meta/online_smote_bagging.py
  src/skmultiflow/meta/online_under_over_bagging.py
  src/skmultiflow/meta/oza_bagging.py
  src/skmultiflow/meta/oza_bagging_adwin.py
  src/skmultiflow/meta/regressor_chains.py
  src/skmultiflow/neural_networks/perceptron.py
  src/skmultiflow/prototype/robust_soft_learning_vector_quantization.py
  src/skmultiflow/trees/arf_hoeffding_tree.py
  src/skmultiflow/trees/extremely_fast_decision_tree.py
  src/skmultiflow/trees/hoeffding_adaptive_tree_regressor.py
  src/skmultiflow/trees/hoeffding_tree.py
  src/skmultiflow/trees/hoeffding_tree_regressor.py
  src/skmultiflow/trees/isoup_tree.py
  src/skmultiflow/trees/label_combination_hoeffding_tree.py
  src/skmultiflow/trees/stacked_single_target_hoeffding_tree_regressor.py
Labels: doc

#220 [BUG/ENHANCEMENT] Coverage tests for HAT/HATR and bug fixes
  src/skmultiflow/trees/arf_hoeffding_tree.py
  src/skmultiflow/trees/extremely_fast_decision_tree.py
  src/skmultiflow/trees/hoeffding_adaptive_tree.py
  src/skmultiflow/trees/hoeffding_adaptive_tree_regressor.py
  src/skmultiflow/trees/hoeffding_tree.py
  src/skmultiflow/trees/hoeffding_tree_regressor.py
  src/skmultiflow/trees/isoup_tree.py
  src/skmultiflow/trees/label_combination_hoeffding_tree.py
  src/skmultiflow/trees/nodes/ada_learning_node.py
  src/skmultiflow/trees/nodes/ada_learning_node_for_regression.py
  src/skmultiflow/trees/nodes/ada_split_node.py
  src/skmultiflow/trees/nodes/ada_split_node_for_regression.py
  src/skmultiflow/trees/nodes/lc_active_learning_node.py
  src/skmultiflow/trees/stacked_single_target_hoeffding_tree_regressor.py
  tests/trees/test_hoeffding_adaptive_tree.py
  tests/trees/test_regression_hoeffding_adaptive_tree.py
Labels: bug, enhancement, test

#226 Fix bug in LeverageBaggingClassifier that resulted in unreachable code during initialisation when using output codes
  docs/api/api.rst
  src/skmultiflow/demos/_test_comparison_prequential.py
  src/skmultiflow/demos/_test_file_stream.py
  src/skmultiflow/demos/_test_file_stream_multiple_cfier.py
  src/skmultiflow/demos/_test_leverage_bagging.py
  src/skmultiflow/demos/_test_prequential_bagging.py
  src/skmultiflow/meta/__init__.py
  src/skmultiflow/meta/leverage_bagging.py
  tests/meta/test_leverage_bagging.py
Labels: bug

#227 Minor maintenance updates
  docker/dockerfiles/devel-jupyter.Dockerfile
  docker/dockerfiles/devel.Dockerfile
  docker/examples/notebooks/QuickStart.ipynb
  docker/examples/src/hoeffding_tree.py
  docker/examples/src/ht_from_file.py
  src/skmultiflow/meta/leverage_bagging.py
Labels: enhancement
